# -*- coding: utf-8 -*-
"""Aula de Introducao ao Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zRdKsH2-USpROJwXWbAqgxV7Hfrb6cDx

## Lógica de Programação - Hacker do Bem
"""

for i in range (11):
  print(i)

"""# print("um texto qualquer")"""

print("Hello World")

print("Digite o seu nome: ")
input()

input("Digite o nome do seu animal de estimação:  ")

variavel_nome = input("Digite o nome do gato:\n")
print(variavel_nome)

frase = input("digite uma frase: ")
frase = "Este texto vai subscrever a frase que foi digitada"
print(frase)

idade = 25
type(idade)

idade ="vinte e cinco"
type(idade)

altura = 1.87

type(altura)

altura = float("1.87")
type (altura)

print (altura)

idade = int(20.6)
type(idade)

texto = str(20)
type (texto)

teste = True
type (teste)

564654+14566+48465

"""# Algoritmo - Cálculo do IMC Índice de massa corporal"""

# Entrada de Dados
altura = input("Digite a sua altura: ")
peso = input("Digite o seu peso: ")
idade = input("Digite a sua idade: ")

# Processamento
altura = float (altura)
peso = float (peso)
idade = int (idade)
imc = peso / (altura * altura)

#Resultado
print("IMC = ", imc)



# Entrada de Dados - Convergindo de imediato os tipos de variáveis
altura = float(input("Digite a sua altura: "))
peso = float(input("Digite o seu peso: "))
idade = int(input("Digite a sua idade: "))

# Processamento
imc = peso / (altura * altura)

#Resultado
print(f"O seu IMC é igual à: {imc:.2f} e a sua idade é igual à: {idade}")

"""# Operadores Relacionais"""

10==6

10!=5

12>7

4>=4

8<=2

a = 3
 a != 3

# Faça um programa na sequência abaixo:
# Recebe um valor e armazena na variável num;
# Recebe outro valor e armazena na variável comparacao
# Converte ambos valores recebido para inteiro
# Realiza a operacao resultado = 2 x num + 3
# Utilize os operadores logicos para comparar se o resultado é maior ou igual a comparacao **\

#Entrada
num = int(input("Digite um número qualquer: "))
comparacao = int(input("Digite outro número para realizar a comparação: "))

#Processamento dos Dados
resultado = 2 * num + 3

#Exibição
print(f"O resultado {resultado} é maior ou igual a {comparacao}")
print(f"o resultado é: {resultado >= comparacao}")

"""# Operadores Lógicos

AND
"""

entrada_1 = True
entrada_2 = False
print (entrada_1 and entrada_2)



entrada_1 = True
entrada_2 = True
print (f"{entrada_1} and {entrada_2} = {entrada_1 and entrada_2}")

((2*2+3) == 7) and ((2+2 != 3))



((2*2+3) == 7) and ((2+2 != 3)) and (5*2==10)

"""OR

"""



entrada_1 = False
entrada_2 = False
resultado =  entrada_1 or entrada_2
print(resultado)



entrada_1 = True
entrada_2 = False
resultado =  entrada_1 or entrada_2
print(resultado)

((2*2+3)==6) or ((2+2) != 4) or ((1+9) !=10)

entrada_1 = True
entrada_2 = False
entrada_3 = True

(entrada_1 and entrada_2) or entrada_3

"""Operador NOT

"""

entrada = True
resultado = not entrada
print(resultado)

entrada = False
resultado = not entrada
print(resultado)

entrada_1 = (2*5)>3
entrada_2 = 13<12
entrada_3 = False

print(not ((entrada_1 and entrada_2) or (entrada_1 and entrada_3)))

"""#Estrutura Condicional

Exemplo 1
"""

idade = int(input("Digite a sua idade:\n"))
if (idade>=18):
  print ("A pessoa é maior de idade")
print ("fim do programa")

"""Exemplo 2"""

idade = int(input("Digite a sua idade:\n"))
if (idade>=18):
  print ("A pessoa é maior de idade")
if (idade<18):
  print ("A pessoa é menor de idade")
print ("fim do programa")

"""Exemplo 3"""

print("Para a pergunta a seguir digite sim ou não: ")
resposta = input("O sorvete de morango é o seu preferido?\n")

if (((resposta == "sim") or (resposta == "Sim") or (resposta == "SIM"))):
   print("Que legal")
   print("Vamos tomar em casquinha")


if ((((resposta == "não") or (resposta == "Não") or (resposta == "NAO") or (resposta == "NÃO")))):
   print("Que triste")
   print("Vamos trocar de sabor")

print("Fim de programa")

"""# Estrutura Condicional Composta

Exemplo 1
"""

#Entrada de dados
media  = int(input("Digite a nota final do aluno: "))

#Processamento
if (media >=50):
  print ("O aluno foi aprovado!")
else:
  print ("O aluno foi reprovado!")
print ("fim de programa")

"""Exemplo 2"""

# Cabeçalho
print('='*43)
print("Responda a pergunta a seguir com sim ou não")
print('='*43)


#Entrada de Dados
resposta = input("O seu time de futebol venceu a última partida que disputou?\n")

#Processamento
if (((resposta == "sim") or (resposta == "Sim") or (resposta == "SIM"))):
   print("Que legal, você deve estar feliz!")

else:
#   ((((resposta == "não") or (resposta == "Não") or (resposta == "NAO") or (resposta == "NÃO")))):
  print("Que triste, você deve estar chateado")

print("Fim de programa")

"""# Estruturas Condicionais Encadeadas"""

#Exemplo Conversão de Notas para conceito
#Nota numérica (n)    Conceito
# n >= 9                 A
# 9 > n >= 7             B
# 7 n >= 6               C
# 6 > n >= 5             D
# n<5                    F

# Entrada de Dados
nota = float(input("Digite a nota do aluno \n"))

# Processamento dos dados
if(nota>=9):
  print("conceito final : A")
elif (nota>=7):
  print("conceito final : B")
elif (nota>=6):
  print("conceito final : C")
elif (nota>=5):
  print("conceito final : D")
else:
  print("conceito final : F")
  print("Fim do programa")

"""# Estrutura de Repetição 23/02/2024

Criar um programa que pergunta ao usuário um número inteiro qualquer e o programa calcula automaticamente a tabuada de 1 até 10 desse número.
"""

# Recebendo o número:
numero = input("Digite um número para cálculo de sua tabuada: \n")

# Convertendo o número para inteiro:
numero = int(numero)

# Exibindo a tabuada do número:
print(f"{numero} x 1 = {numero*1}")
print(f"{numero} x 2 = {numero*2}")
print(f"{numero} x 3 = {numero*3}")
print(f"{numero} x 4 = {numero*4}")
print(f"{numero} x 5 = {numero*5}")
print(f"{numero} x 6 = {numero*6}")
print(f"{numero} x 7 = {numero*7}")
print(f"{numero} x 8 = {numero*8}")
print(f"{numero} x 9 = {numero*9}")
print(f"{numero} x 10 = {numero*10}")

"""Com o uso do While"""

# Recebendo o número:
numero = input("Digite um número para cálculo de sua tabuada: \n")

# Convertendo o número para inteiro:
numero = int(numero)

# Criando a varIável de controle do laço para repetição
contador = 1
while(contador<=10):
  # Exibindo o valor da tabuada:
  print(f"{numero} x {contador} = {numero*contador}")
  contador = contador + 1
print("Fim do programa")

"""# Exemplo 2"""

# Recebendo a idade dos usuários
id1 = input("Digite a primeira idade: \n")
id2 = input("Digite a segunda idade: \n")
id3 = input("Digite a terceira idade: \n")
id4 = input("Digite a quarta idade: \n")
id5 = input("Digite a quinta idade: \n")

# Convertendo o número para inteiro
id1 = int(id1)
id2 = int(id2)
id3 = int(id3)
id4 = int(id4)
id5 = int(id5)

# Calculando a média:
media = (id1+id2+id3+id4+id5)/5

# Exibindo a média das idades
print(f"A média das idades é igual à  {media}")

"""Com o uso do While"""

# Criando a variável de controle do laço, contando 5 repetições
contador = 1

# Criando uma variável para acumular os valores das idades digitadas:
soma = 0

# Criando o laço de repetição para receber 5 idades e somá-las:
while(contador <=5):
  # Recebendo a idade do usuário
  idade = int(input(f"Digite a idade do usuário nº {contador}:7  "))

  # Somando a idade do usuário ao valor atual da variável acumulador
  soma = soma + idade

  # Incrementando a variável contador para controle do laço
  contador = contador + 1

# calculando a média das idades
media = soma/(contador-1)
print(f"A média das idades digitadas é igual a: {media}")

"""# Comando FOR"""

# range(inicio,final,incremento)
for cont in range (0,10,1):
  print(cont)

# range(inicio,final,incremento)
for cont in range (10):
  print(cont)

# range(inicio,final,incremento)
for cont in range (0,10):
  print(cont)

# Contagem decrescente
# range(inicio,final,decremento)
for d in range (10,0,-1):
  print(d)

"""Realizar tabuada"""

#Entrada de Dados
num = int(input("Digite um número para o cálculo de sua tabuada: "))
print(f"\nCalculando a tabuada do {num}: \n")
for i in range(1,11,1):
  print(f"{num} x {i} = {num * i}")